// Builds web-sized versions of the showroom photos and publishes them to Convex file storage.
//
//   npm run media:sync      resize, upload new or changed files to Convex, write assets/media-manifest.js
//   npm run media:preview   resize into .media-build/ and point the manifest there, for local preview only
//
// Photos and their captions are listed in media/catalog.json. Originals are read from
// MEDIA_SOURCE_DIR (default "./NEW SHOWROOM"). Convex settings come from .env (see .env.example).

import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import sharp from "sharp";
import { ConvexHttpClient } from "convex/browser";
import { anyApi } from "convex/server";

const mode = process.argv[2];
const prune = process.argv.includes("--prune");
if (!["sync", "preview"].includes(mode)) {
    console.error("Usage: node scripts/media.mjs <sync|preview> [--prune]");
    process.exit(1);
}

if (existsSync(".env")) process.loadEnvFile(".env");

const SOURCE_DIR = process.env.MEDIA_SOURCE_DIR || "./NEW SHOWROOM";
const PREVIEW_DIR = ".media-build";
const MANIFEST_PATH = "assets/media-manifest.js";
const catalog = JSON.parse(readFileSync("media/catalog.json", "utf8"));

let client;
let secret;
let remote = new Map();
if (mode === "sync") {
    const url = process.env.CONVEX_URL;
    secret = process.env.MEDIA_UPLOAD_SECRET;
    if (!url || !secret) {
        console.error("Set CONVEX_URL and MEDIA_UPLOAD_SECRET in .env first (see .env.example).");
        process.exit(1);
    }
    client = new ConvexHttpClient(url);
    for (const row of await client.query(anyApi.media.list, {})) remote.set(row.key, row);
} else {
    mkdirSync(PREVIEW_DIR, { recursive: true });
}

const missing = catalog.items.filter((item) => !existsSync(join(SOURCE_DIR, item.file)));
if (missing.length) {
    console.error(`Missing originals in ${SOURCE_DIR}: ${missing.map((item) => item.file).join(", ")}`);
    process.exit(1);
}

async function publish(key, buffer, info) {
    if (mode === "preview") {
        const file = join(PREVIEW_DIR, key.replaceAll("/", "__"));
        writeFileSync(file, buffer);
        return `./${file}`;
    }
    const sha256 = createHash("sha256").update(buffer).digest("hex");
    const existing = remote.get(key);
    if (existing?.sha256 === sha256 && existing.url) return existing.url;

    const uploadUrl = await client.mutation(anyApi.media.generateUploadUrl, { secret });
    const response = await fetch(uploadUrl, { method: "POST", headers: { "Content-Type": "image/webp" }, body: buffer });
    if (!response.ok) throw new Error(`Upload failed for ${key}: ${response.status} ${await response.text()}`);
    const { storageId } = await response.json();
    const url = await client.mutation(anyApi.media.save, {
        secret,
        key,
        storageId,
        sha256,
        contentType: "image/webp",
        size: buffer.length,
        width: info.width,
        height: info.height,
    });
    console.log(`  ↑ ${key}`);
    return url;
}

const items = [];
const keys = new Set();
for (const item of catalog.items) {
    const source = sharp(join(SOURCE_DIR, item.file)).rotate();
    const { dominant } = await source.clone().stats();
    const sizes = [];
    for (const target of catalog.widths) {
        const { data, info } = await source
            .clone()
            .resize({ width: target, height: target, fit: "inside", withoutEnlargement: true })
            .webp({ quality: 78, effort: 5 })
            .toBuffer({ resolveWithObject: true });
        if (sizes.some((size) => size.w === info.width)) continue;
        const key = `gallery/${item.id}-${info.width}.webp`;
        keys.add(key);
        sizes.push({ w: info.width, h: info.height, url: await publish(key, data, info) });
    }
    const largest = sizes[sizes.length - 1];
    items.push({
        id: item.id,
        caption: item.caption,
        alt: item.alt,
        group: item.group,
        gallery: item.gallery !== false,
        width: largest.w,
        height: largest.h,
        color: `rgb(${dominant.r}, ${dominant.g}, ${dominant.b})`,
        sizes: sizes.map(({ w, url }) => ({ w, url })),
    });
    console.log(`✓ ${item.id} (${item.file})`);
}

if (mode === "sync" && prune) {
    for (const key of remote.keys()) {
        if (keys.has(key)) continue;
        await client.mutation(anyApi.media.remove, { secret, key });
        console.log(`  ✗ retired ${key}`);
    }
    // Replaced and removed files are kept for a while so deployed pages using the old manifest still load.
    for (const key of await client.mutation(anyApi.media.purgeRetired, { secret, olderThanDays: 30 })) {
        console.log(`  ✗ deleted old copy of ${key}`);
    }
}

const manifest = { generated: new Date().toISOString(), source: mode === "sync" ? "convex" : "preview", groups: catalog.groups, items };
writeFileSync(
    MANIFEST_PATH,
    `// Generated by \`npm run media:${mode}\`. Edit media/catalog.json and re-run it instead of editing this file.\n` +
        `window.SHOWROOM_MEDIA = ${JSON.stringify(manifest, null, 2)};\n`,
);
console.log(`\nWrote ${MANIFEST_PATH} with ${items.length} photos (${mode}).`);
if (mode === "preview") console.log("This manifest points at local files. Run `npm run media:sync` before committing.");
